baseURL = 'https://bloat-free.com/'
languageCode = 'en-us'
title = 'bloat-free.com'
enableEmoji = true
summaryLength = 70

[pagination]
  pagerSize = 5

[params]
  description = "Just content. No clutter."
  author = "Leorium"
  mainSections = ["posts"]
  youtubeChannel = "@leorium"
  githubHandle = "LeoriumDev"
  dateFormat = "Jan 2, 2006"
  showReadingTime = true
  showPostNavigation = true
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

[taxonomies]
  tag = "tags"
